### ISSUE TITLE
Make repo public or invite some additional collaborators

### ISSUE THREAD

**Issue by mattyschell** [cmenedes/doitt-expire-notif#1]
What do you think can this be repo be public?  If not (or not, for now) can you please invite Mohammed to collaborate?  I'd like to have him review the specifications you've laid out in the README.

**Comment by cmenedes** [comment]
Yeah, it can be public, especially since we are omitting some key info.

**Comment by mattyschell** [comment]
Great, please do!  And [edit] please close this issue, get those green dots on the contributions chart nice and speckled.  

I'll loop in Mohammed today if he has time.
